project:
  name: quickstart-ibm-integration
  shorten_stack_name: true
  s3_regional_buckets: true
  package_lambda: false
  s3_bucket: ''
  regions:
  - eu-west-1
  - eu-west-2
  - ca-central-1
  
tests:
  cp4i:
    parameters:
      NumberOfAZs: '3'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      BootNodeAccessCIDR: override
      DomainName: override
      KeyPairName: override
      NumberOfMaster: '3'
      NumberOfCompute: '3'
      ClusterName: cp4i-$[taskcat_random-string]
      RedhatPullSecret: override
      APIKey: override
      APIUsername: override
      LicenseAgreement: I agree
      Namespace: integration
      APILM: 'True'
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-ibm-integration/
      CP4IDeploymentLogsBucketName: override
    regions:  
    - ca-central-1
    - eu-west-1
    template: templates/ibm-cloudpak-root.template.yaml