== Software licenses 

This Quick Start deploys the Cloud Pak for Integration environment by using an AWS CloudFormation template. You can use it to build a new VPC for your Cloud Pak for Integration on AWS cluster. You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using the Quick Start.

The AWS CloudFormation template for this Quick Start includes configuration parameters that you can customize. Some of these settings, such as instance type, will affect the cost of deployment. For cost estimates, see the pricing pages for each AWS service you will be using. Prices are subject to change.

*Tip* After you deploy the Quick Start, we recommend that you enable the https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-gettingstarted-turnonreports.html[AWS Cost and Usage Report] to track costs associated with the Quick Start. This report delivers billing metrics to an Amazon Simple Storage Service (Amazon S3) bucket in your account. It provides cost estimates based on usage throughout each month, and finalizes the data at the end of the month. For more information about the report, see the https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-costusage.html[AWS documentation].

You can get started with a 60 day trial period or use your existing Cloud Pak for Integration entitlement. You also have the option to use an evaluation version of OpenShift Container Platform (OCP) and OpenShift Container Storage (OCS), or to use your existing entitlement to those components.

To get pricing information, or to use your existing Cloud Pak for Integration entitlements, contact your IBM sales representative.

For more information on licensing terms, see the Cloud Pak for Integration http://ibm.biz/cp4i-license[software license agreement].

== 
