== Prerequisites

=== Technical requirements

For Red Hat OpenShift installation requirements, see https://docs.openshift.com/container-platform/4.4/welcome/index.html[Planning your installation].

For Cloud Pak for Integration requirements, see https://www.ibm.com/support/knowledgecenter/SSGT7J_20.3/install/sysreqs.html[System requirements for Cloud Pak for Integration].

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/architecture/architecture-rhcos[Red Hat Enterprise Linux CoreOS (RHCOS)] is used for the OpenShift EC2 instances in this deployment.

Before you launch the Quick Start, your account must be configured as specified in the following table. Otherwise, deployment might fail.

[cols=",",]
|===
|http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html[Resources] a|
If necessary, request https://console.aws.amazon.com/servicequotas/home?region=us-east-1#!/[service quota increases] for the following resources. You might need to do this if an existing deployment uses these resources, and you might exceed the default quotas with this deployment. The https://console.aws.amazon.com/servicequotas/home?region=us-east-1#!/[Service Quotas console] displays your usage and quotas for some aspects of some services. For more information, see the https://docs.aws.amazon.com/servicequotas/latest/userguide/intro.html[AWS documentation].

[cols=",",options="header",]
|===
|Resource |This deployment uses
|VPCs |1
|Elastic IP addresses |3
|Network Load Balancers |2
|Classic Load Balancers |3
|i3.large instances |1
|m5.2xlarge instances |3
|m5.8xlarge instances |3
|m4.4xlarge instances |3 (if OCS dedicated)
|===

|https://aws.amazon.com/about-aws/global-infrastructure/[Regions] |This deployment includes 3 Availability Zones, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html[Service Endpoints and Quotas] in the AWS documentation.
|https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[Key pair] a|
Make sure that at least one Amazon EC2 key pair exists in your AWS account in the Region where you are planning to deploy the Quick Start. Make note of the key pair name. You’ll be prompted for this information during deployment. To create a key pair, follow the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[instructions in the AWS documentation].

If you’re deploying the Quick Start for testing or proof-of-concept purposes, we recommend that you create a new key pair instead of specifying a key pair that’s already being used by a production instance.

|https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html[IAM permissions] |To deploy the Quick Start, you must log in to the AWS Management Console with AWS Identity and Access Management (IAM) permissions for the resources and actions the templates will deploy. The _AdministratorAccess_ managed policy within IAM provides sufficient permissions, although your organization may choose to use a custom policy with more restrictions.
|===
